global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'node'
    ec2_sd_configs:
      - region: us-east-1
        access_key: AKIAXA2CYSA26VEZ7CAA
        secret_key: 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
        port: 9100
